apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecosia-deployment
  labels:
    app: ecosia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecosia
  template:
    metadata:
      labels:
        app: ecosia
    spec:
      containers:
      - name: ecosia
        image: ajaykatke/web:3.0
        ports:
        - containerPort: 2022
